services:
  - type: web
    name: ticket-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    plan: free
    autoDeploy: true
    region: frankfurt
